## Prueba de las transformaciones de los datos

In [2]:
import pandas as pd
schedule = pd.read_csv(r"C:\Users\poloc\Documents\PruebasGit\Primera prueba\data\raw\staff_schedule.csv")
patients = pd.read_csv(r"C:\Users\poloc\Documents\PruebasGit\Primera prueba\data\raw\patients.csv")
staff = pd.read_csv(r"C:\Users\poloc\Documents\PruebasGit\Primera prueba\data\raw\staff.csv")
service = pd.read_csv(r"C:\Users\poloc\Documents\PruebasGit\Primera prueba\data\raw\services_weekly.csv")

### Transformaciones

In [7]:

patients["arrival_date"] = pd.to_datetime(patients["arrival_date"], format="%Y-%m-%d")
patients["departure_date"] = pd.to_datetime(patients["departure_date"], format="%Y-%m-%d")
patients["arrival_week"] = patients["arrival_date"].dt.isocalendar().week.astype(int)
patients["departure_week"] = patients["departure_date"].dt.isocalendar().week.astype(int)
patients.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction,arrival_week,departure_week
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61,11,12
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83,50,50
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83,26,27
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81,41,43
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76,8,9

In [8]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patient_id      1000 non-null   object
 1   name            1000 non-null   object
 2   age             1000 non-null   int64
 3   arrival_date    1000 non-null   datetime64[ns]
 4   departure_date  1000 non-null   datetime64[ns]
 5   service         1000 non-null   object
 6   satisfaction    1000 non-null   int64
 7   arrival_week    1000 non-null   int64
 8   departure_week  1000 non-null   int64
dtypes: datetime64[ns](2), int64(4), object(3)
memory usage: 70.4+ KB

In [ ]:
service["shift_id"] = range(1, len(service) + 1)
service["shift_id"] = service["shift_id"].astype(str)

In [11]:
service.head()

,week,month,service,available_beds,patients_request,patients_admitted,patients_refused,patient_satisfaction,staff_morale,event,shift_id
0,1,1,emergency,32,76,32,44,67,70,none,1
1,1,1,surgery,45,130,45,85,83,78,flu,2
2,1,1,general_medicine,37,201,37,164,97,43,flu,3
3,1,1,ICU,22,31,22,9,84,91,flu,4
4,2,1,emergency,28,169,28,141,75,64,none,5

In [12]:
service.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   week                  208 non-null    int64
 1   month                 208 non-null    int64
 2   service               208 non-null    object
 3   available_beds        208 non-null    int64
 4   patients_request      208 non-null    int64
 5   patients_admitted     208 non-null    int64
 6   patients_refused      208 non-null    int64
 7   patient_satisfaction  208 non-null    int64
 8   staff_morale          208 non-null    int64
 9   event                 208 non-null    object
 10  shift_id              208 non-null    object
dtypes: int64(8), object(3)
memory usage: 18.0+ KB

In [14]:
schedule = schedule[["week", "staff_id", "present"]]
schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6552 entries, 0 to 6551
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   week      6552 non-null   int64
 1   staff_id  6552 non-null   object
 2   present   6552 non-null   int64
dtypes: int64(2), object(1)
memory usage: 153.7+ KB

In [15]:
schedule.head()

   week      staff_id  present
0     1  STF-b77cdc60        1
1     2  STF-b77cdc60        1
2     3  STF-b77cdc60        0
3     4  STF-b77cdc60        1
4     5  STF-b77cdc60        1

In [16]:
staff.head()

       staff_id       staff_name    role    service
0  STF-5ca26577     Allison Hill  doctor  emergency
1  STF-02ae59ca      Noah Rhodes  doctor  emergency
2  STF-d8006e7c  Angie Henderson  doctor  emergency
3  STF-212d8b31    Daniel Wagner  doctor  emergency
4  STF-107a58e4  Cristian Santos  doctor  emergency